import { describe, expect, it } from 'vitest';
import { analyzeObservations, isSupportedMetric, recommendationForInsight, type MetricObservation } from '../lib/learning-loop';
const daysAgo = (days: number) => new Date(Date.now() - days * 86400000).toISOString();
describe('learning loop analytics', () => {
 it('allows only explicitly supported metrics', () => { expect(isSupportedMetric('engagement_rate')).toBe(true); expect(isSupportedMetric('followers_private_token')).toBe(false); });
 it('compares adjacent periods and retains evidence and sample sizes', () => { const rows: MetricObservation[] = [{metric_key:'engagement_rate',platform:'instagram',value:2,observed_at:daysAgo(13)},{metric_key:'engagement_rate',platform:'instagram',value:2.2,observed_at:daysAgo(10)},{metric_key:'engagement_rate',platform:'instagram',value:3,observed_at:daysAgo(4)},{metric_key:'engagement_rate',platform:'instagram',value:3.2,observed_at:daysAgo(1)}]; const result = analyzeObservations(rows); expect(result).toHaveLength(1); expect(result[0].insight_type).toBe('winner'); expect(result[0].sample_size_previous).toBe(2); expect(result[0].sample_size_current).toBe(2); expect(result[0].evidence).toHaveLength(2); expect(result[0].relative_change).toBeGreaterThan(0.15); });
 it('does not infer trends from one observation per period', () => { const rows: MetricObservation[] = [{metric_key:'likes',platform:'instagram',value:10,observed_at:daysAgo(10)},{metric_key:'likes',platform:'instagram',value:30,observed_at:daysAgo(1)}]; expect(analyzeObservations(rows)).toHaveLength(0); });
 it('does not fabricate percentage change from a zero baseline', () => { const rows: MetricObservation[] = [{metric_key:'clicks',platform:'linkedin',value:0,observed_at:daysAgo(13)},{metric_key:'clicks',platform:'linkedin',value:0,observed_at:daysAgo(10)},{metric_key:'clicks',platform:'linkedin',value:3,observed_at:daysAgo(4)},{metric_key:'clicks',platform:'linkedin',value:5,observed_at:daysAgo(1)}]; const result = analyzeObservations(rows); expect(result).toHaveLength(1); expect(result[0].relative_change).toBeNull(); expect(result[0].finding).toContain('zero baseline'); });
 it('keeps expected impact non-numeric without causal evidence', () => { const rows: MetricObservation[] = [{metric_key:'shares',platform:'instagram',value:10,observed_at:daysAgo(13)},{metric_key:'shares',platform:'instagram',value:12,observed_at:daysAgo(10)},{metric_key:'shares',platform:'instagram',value:2,observed_at:daysAgo(4)},{metric_key:'shares',platform:'instagram',value:3,observed_at:daysAgo(1)}]; const rec = recommendationForInsight(analyzeObservations(rows)[0]); expect(rec.expected_impact.estimate).toBeNull(); expect(rec.action_type).toBe('test_alternative'); expect(rec.risk_level).toBe('low'); });
 it('ignores unsupported metrics and negative values', () => { const rows: MetricObservation[] = [{metric_key:'likes',platform:'instagram',value:-1,observed_at:daysAgo(13)},{metric_key:'likes',platform:'instagram',value:2,observed_at:daysAgo(10)},{metric_key:'likes',platform:'instagram',value:3,observed_at:daysAgo(4)},{metric_key:'likes',platform:'instagram',value:4,observed_at:daysAgo(1)},{metric_key:'private_metric',platform:'instagram',value:500,observed_at:daysAgo(1)}]; expect(analyzeObservations(rows)).toHaveLength(0); });
});
