import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
const migration = (name: string) => readFileSync(resolve(process.cwd(), "supabase/migrations", name), "utf8");
describe("workflow migration integrity", () => {
 it("hardens campaign selection transactionally", () => { const sql = migration("20261008001825_009_transactional_workflows.sql"); expect(sql).toContain("create or replace function public.select_campaign_package"); expect(sql).toContain("for update"); expect(sql).toContain("insert into content_drafts"); expect(sql).toContain("update campaigns"); });
 it("hardens review state transitions transactionally", () => { const sql = migration("20261008001825_009_transactional_workflows.sql"); expect(sql).toContain("create or replace function public.review_content_draft"); expect(sql).toContain("Only workspace owners and admins can review content."); expect(sql).toContain("update approvals set status"); expect(sql).toContain("update content_drafts set status"); });
 it("prevents campaign drafts with missing media from entering approval", () => { const sql = migration("20261009000800_campaign_media_approval_guard.sql"); expect(sql).toContain("enforce_campaign_media_readiness"); expect(sql).toContain("Required campaign media must be generated before submitting or approving this draft."); expect(sql).toContain("media_status := 'pending'"); });
 it("creates an append-only, workspace-isolated campaign usage ledger", () => { const sql = migration("20261009000900_campaign_usage_ledger.sql"); expect(sql).toContain("create table if not exists public.campaign_usage_events"); expect(sql).toContain("alter table public.campaign_usage_events enable row level security"); expect(sql).toContain("private.is_workspace_member(workspace_id)"); expect(sql).toContain("actor_user_id = (select auth.uid())"); expect(sql).toContain("result_status in ('generated','media_pending','failed')"); expect(sql).toContain("on public.campaign_usage_events for insert"); expect(sql).not.toContain("on public.campaign_usage_events for update"); expect(sql).not.toContain("on public.campaign_usage_events for delete"); });
 it("keeps provider-reported costs distinct from product credit estimates", () => { const sql = migration("20261009001000_campaign_provider_usage.sql"); expect(sql).toContain("provider_cost_usd numeric(14,8)"); expect(sql).toContain("cost_source in ('provider_reported','partial','not_available','demo')"); expect(sql).toContain("NULL means unknown, not free"); expect(sql).toContain("prompt_tokens bigint"); expect(sql).toContain("total_tokens bigint"); });
 it("adds the persistent learning loop foundation with tenant isolation", () => { const sql = migration("20261009000354_agent_learning_foundation.sql"); expect(sql).toContain("create table if not exists public.agent_memories"); expect(sql).toContain("create table if not exists public.performance_insights"); expect(sql).toContain("create table if not exists public.agent_recommendations"); expect(sql).toContain("alter table public.agent_memories enable row level security"); expect(sql).toContain("alter table public.performance_insights enable row level security"); expect(sql).toContain("alter table public.agent_recommendations enable row level security"); expect(sql).toContain("private.is_workspace_member(workspace_id)"); expect(sql).toContain("risk_level in ('low','medium','high','critical')"); });
 it("serializes campaign credit reservations against workspace monthly budgets", () => { const sql = migration("20261009001100_workspace_usage_budgets.sql"); expect(sql).toContain("create table if not exists public.workspace_usage_budgets"); expect(sql).toContain("create table if not exists public.campaign_usage_reservations"); expect(sql).toContain("for update"); expect(sql).toContain("create or replace function public.reserve_campaign_usage"); expect(sql).toContain("create or replace function public.finalize_campaign_usage_reservation"); expect(sql).toContain("workspace_forbidden"); expect(sql).toContain("campaign_execution_forbidden"); expect(sql).toContain("interval '30 minutes'"); });
});
describe("social publication integrity", () => {
 it("audits publication attempts and prevents duplicate active or successful posts", () => {
  const sql = migration("20261009001300_linkedin_publication_audit.sql");
  expect(sql).toContain("create table if not exists public.social_publications");
  expect(sql).toContain("alter table public.social_publications enable row level security");
  expect(sql).toContain("where status in ('pending','published','unknown')");
  expect(sql).toContain("provider_post_id is not null");
  expect(sql).toContain("workspace admins can view social publications");
  expect(sql).toContain("workspace admins can create social publications");
 });
});
