export type MetricObservation = { metric_key: string; value: number; platform: string; observed_at: string; post_ref?: string | null; source_type?: string };
export type LearningInsight = { insight_type: 'trend' | 'winner' | 'underperformer'; platform: string; metric_key: string; period_start: string; period_end: string; previous_average: number; current_average: number; absolute_change: number; relative_change: number | null; sample_size_previous: number; sample_size_current: number; finding: string; confidence: number; evidence: Array<{ period: string; count: number; average: number }> };
const DAY_MS = 86400000;
const SUPPORTED = new Set(['impressions','reach','likes','comments','shares','saves','clicks','engagement_rate','conversions']);
export function isSupportedMetric(metric: string): boolean { return SUPPORTED.has(metric); }
const avg = (values: number[]) => values.reduce((sum, value) => sum + value, 0) / values.length;
/** Compare adjacent periods; a trend requires at least two observations per period. */
export function analyzeObservations(observations: MetricObservation[], now = new Date(), windowDays = 7): LearningInsight[] {
 const end = now.getTime(), currentStart = end - windowDays * DAY_MS, previousStart = end - 2 * windowDays * DAY_MS;
 const groups = new Map<string, MetricObservation[]>();
 for (const item of observations) { const t = Date.parse(item.observed_at); if (!isSupportedMetric(item.metric_key) || !Number.isFinite(item.value) || item.value < 0 || !Number.isFinite(t) || t < previousStart || t > end) continue; const key = item.platform.trim().toLowerCase() + '|' + item.metric_key; groups.set(key, [...(groups.get(key) ?? []), item]); }
 const insights: LearningInsight[] = [];
 for (const [key, group] of groups) { const [platform, metric_key] = key.split('|'); const previous = group.filter(x => { const t = Date.parse(x.observed_at); return t >= previousStart && t < currentStart; }); const current = group.filter(x => { const t = Date.parse(x.observed_at); return t >= currentStart && t <= end; }); if (previous.length < 2 || current.length < 2) continue;
  const previous_average = avg(previous.map(x => x.value)), current_average = avg(current.map(x => x.value)), absolute_change = current_average - previous_average; const relative_change = previous_average === 0 ? (current_average === 0 ? 0 : null) : absolute_change / previous_average; if (relative_change !== null && Math.abs(relative_change) < 0.15) continue;
  const direction = absolute_change > 0 ? 'increased' : absolute_change < 0 ? 'decreased' : 'was unchanged'; const amount = relative_change === null ? 'from a zero baseline' : (Math.abs(relative_change) * 100).toFixed(1) + '%'; const total = previous.length + current.length;
  insights.push({ insight_type: absolute_change >= 0 ? 'winner' : 'underperformer', platform, metric_key, period_start: new Date(previousStart).toISOString(), period_end: new Date(end).toISOString(), previous_average: Number(previous_average.toFixed(4)), current_average: Number(current_average.toFixed(4)), absolute_change: Number(absolute_change.toFixed(4)), relative_change: relative_change === null ? null : Number(relative_change.toFixed(4)), sample_size_previous: previous.length, sample_size_current: current.length, finding: metric_key + ' on ' + platform + ' ' + direction + ' by ' + amount + ' versus the preceding ' + windowDays + '-day period.', confidence: Number(Math.min(0.95, 0.5 + Math.min(total, 18) / 40).toFixed(4)), evidence: [{ period: 'previous', count: previous.length, average: Number(previous_average.toFixed(4)) }, { period: 'current', count: current.length, average: Number(current_average.toFixed(4)) }] });
 }
 return insights.sort((a,b) => Math.abs(b.relative_change ?? 0) - Math.abs(a.relative_change ?? 0));
}
export function recommendationForInsight(insight: LearningInsight) { const improving = insight.absolute_change > 0; return { action_type: improving ? 'replicate_pattern' : 'test_alternative', title: improving ? 'Replicate the stronger ' + insight.platform + ' pattern' : 'Run a controlled alternative on ' + insight.platform, rationale: insight.finding + ' Treat this as directional evidence, not proof of causality.', evidence: [{ metric_key: insight.metric_key, platform: insight.platform, previous_average: insight.previous_average, current_average: insight.current_average, relative_change: insight.relative_change, sample_size_previous: insight.sample_size_previous, sample_size_current: insight.sample_size_current, period_start: insight.period_start, period_end: insight.period_end }], expected_impact: { direction: improving ? 'positive' : 'uncertain', metric_key: insight.metric_key, estimate: null, note: 'No numeric lift forecast is made; validate with a controlled test.' }, risk_level: 'low', priority: Math.abs(insight.relative_change ?? 0) >= 0.3 ? 'high' : 'normal' } as const; }
